services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
     - 8080:80
    links:
      -php
    volumes:
      - ./www/html:/usr/share/nginx/html/

  php:
    image: php:7.0-fpm
    container_name: php_container
    expose:
      - 9000
    volumes:
      - ./www/html:/usr/share/nginx/html/

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mpdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password

networks:
  webnet: {}
