services:
  nginx:
    build: ./nginx/
    container_name: nginx_container
    ports:
     - 8080:80
    links:
      - php
    volumes:
      - ./www/html:/usr/share/nginx/html/

  php:
    build: ./php/
    container_name: php_container
    links:
      - mysql
    expose:
      - 9000
    volumes:
      - ./www/html:/usr/share/nginx/html/

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mpdb  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: password

  phpadmin:
    image: phpmyadmin:latest
    container_name: admin_container
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

networks:
  webnet: {}
