services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
     - 8080:80
    links:
      - php
    volumes:
      - ./www/html:/usr/share/nginx/html/

  php:
    build: ./php/
    container_name: php_container
    links:
      - mysql
    expose:
      - 9000
    volumes:
      - ./www/html:/usr/share/nginx/html/

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: password

networks:
  webnet: {}
